[tasks.dist]
description = "Build a release bundle for GitHub Pages deployment"
command = "dx"
# Voodoo magic:
# 1. `dx bundle` doesn't work with --ssg (it supports the flags, but doesn't do
# anything) so we have to used `dx build`.
# 2. `dx build --ssg` sometimes overwrites the SSG artifacts with the web client
# artifacts, so we have to force sequential execution to ensure the SSG artifacts
# are generated last.
# 3. `wasm-opt` fails on aarch64 with debug symbols, so we have to disable them.
args = ["build", "--release", "--ssg", "--force-sequential", "--debug-symbols=false"]

[tasks.move-public]
description = "Move files out of build directory to docs/ for GitHub Pages"
dependencies = ["dist"]
script_runner = "powershell"
script_extension = "ps1"
script = '''
if (Test-Path docs) {
    Remove-Item docs -Recurse -Force
}
Move-Item $env:CARGO_MAKE_CRATE_TARGET_DIRECTORY/dx/$env:CARGO_MAKE_CRATE_NAME/release/web/public docs -Force
'''

[tasks.fix-404]
description = "Fix location of 404 page for GitHub Pages client-side routing"
dependencies = ["move-public"]
script_runner = "powershell"
script_extension = "ps1"
script = '''
Move-Item docs/404/index.html docs/404.html -Force
Remove-Item docs/404 -Recurse -Force
'''

[tasks.deploy]
description = "Full GitHub Pages deployment build"
dependencies = ["fix-404"]
